### ISSUE TITLE
Icon for SD-Card Operations missing

### ISSUE THREAD

**Issue by RodneyMcKay715** [ntoff/Octoprint-CyborgTheme#11]
The Icon for SD-Card Operations is missing:

http://imgur.com/a/tL1ZM

**Comment by ntoff** [comment]
ok, just went looking and the SD icon isn't part of font-awesome, it's a separate gif, and it's black so looks like I'll have to create a white version of it and upload separately and add it's own css entry. Thanks for letting me know.

**Comment by ntoff** [comment]
fixed (I hope) with https://github.com/ntoff/Octoprint-CyborgTheme/commit/643642181558f9f061af3abb74b31d75a11265f9 

edit: or not, that somehow broke the overflow in the temperature dropdown

**Comment by ntoff** [comment]
Ok really fixed this time: https://github.com/ntoff/Octoprint-CyborgTheme/commit/cac9f9bdc827ea659086af46a0e73bb3ef7ea312

missed the closing curlybrace and the syntax highlighter didn't catch it :(
