### ISSUE TITLE
icons are broken in octoprint 1.3.5 and up

### ISSUE THREAD

**Issue by ntoff** [ntoff/Octoprint-CyborgTheme#15]
Tested: OctoPrint 1.3.5.dev52+g6a1b162 (maintenance branch)

Thanks to the move to the new fontawesome, some icons might be black on black, some red ones are green, the snozzberries still taste like snozzberries

delete icons are no longer red in timelapse management
![image](https://user-images.githubusercontent.com/9030085/26926826-8126aa90-4c92-11e7-8902-e2c3cb85c73a.png)

invisible icons in access control
![image](https://user-images.githubusercontent.com/9030085/26926843-993545b0-4c92-11e7-8794-87a135834064.png)

delete icons no longer red in plugin manager
![image](https://user-images.githubusercontent.com/9030085/26926924-fa4308b0-4c92-11e7-8634-9834c85867c9.png)

**Comment by ntoff** [comment]
fixed in https://github.com/ntoff/Octoprint-CyborgTheme/tree/0.1.3 

SD icon is still higher than it should be, not my fault, it's that way in vanilla octoprint.
![image](https://user-images.githubusercontent.com/9030085/26943331-86853d90-4cc8-11e7-91b8-84b21f7fc146.png)

**Comment by ntoff** [comment]
as of OctoPrint 1.3.5rc2 (rc/maintenance branch)

terminal filters are misaligned (they're not supposed to be in the middle)
![image](https://user-images.githubusercontent.com/9030085/28752460-47f3d168-7563-11e7-9efa-234f69d65273.png)

on/off switches are possibly a bit confusing now.  is white on or off? which bit is white and which is black? is the black bit the knob or the indicator?
![image](https://user-images.githubusercontent.com/9030085/28752470-aa883b5c-7563-11e7-9fc8-bfeb3e575dd2.png)

**Comment by ntoff** [comment]
Possibly fixed in https://github.com/ntoff/Octoprint-CyborgTheme/tree/stripped_down

If anyone but me sees this, would anyone like to test it by manually installing the stripped down branch. I've removed a TONNE of stuff from the original theme to cut down on formatting conflicts so the more eyeballs that test it the better. The button to en/disable the plugins is still the same, there's really no changing that from the theme's point of view and changing the colours made it seem a little weird. If anyone has any suggestions, let me know.

Hit up the plugin installer and manually install from this url please: https://github.com/ntoff/Octoprint-CyborgTheme/archive/stripped_down.zip

**Comment by Leonas** [comment]
The stripped down branch works great with the latest Octoprint. Thanks for making this -- Octoprint has never looked better!

**Comment by jneilliii** [comment]
Thank you for this ntoff.  The stripped down version is working for me in the new OctoPrint as well, with the minor exception of the temperature menus.  Not sure if this was the case on stock.

![image](https://user-images.githubusercontent.com/5249455/29649415-decb4380-8861-11e7-9246-6e76b814c089.png)

**Comment by jneilliii** [comment]
Ok, so just disabled the plugin and the stock octoprint has this same issue.  However, I did find another spot that could be tweaked a little possibly.  In one of my plugins selected items in a multi select list are difficult to see.  Here's the comparison.




![image](https://user-images.githubusercontent.com/5249455/29649666-7f8885de-8863-11e7-8edc-861d87f53707.png)

![image](https://user-images.githubusercontent.com/5249455/29649662-72e4c194-8863-11e7-98fe-92e497801fb7.png)

**Comment by ntoff** [comment]
Unfortunately that temperature control wrapping (as you've found out) is bootstrap's evil doing https://github.com/foosel/OctoPrint/issues/2059 and I probably could "fix" it by messing about with bootstrap, I'd like to avoid changing anything that interferes with octoprint's core mechanics. It seems to be related to something bootstrap does when touch capabilities are enabled.

As for the plugin, I assume it's just called "detailed progress"? I'll take a look & see if it needs a specific override or whether I should just make all selections darker or something.

**Comment by ntoff** [comment]
@jneilliii Could you try something please? Could you try adding your own css to your plugin and add this:

    div#settings_plugin_detailedprogress select[multiple] {
        background-color: inherit;
        color: inherit;
    }

Just add a folder under static called "css" and put your stylesheet in there and modify `__init__.py`

![image](https://user-images.githubusercontent.com/9030085/29654448-9bd5626a-88f0-11e7-9a7f-8729adc1d772.png)

	
That should set your select box based on the base colour of the page. That way if anyone else makes a different theme, your plugin should (hopefully) follow their colour scheme. I can add it to my theme but then it'll only work with my theme, adding it to your plugin *should* hopefully make it work with any future themes as well. As a side note, I don't think you can actually style those multi select boxes, they seem to be set by the browser (the only thing you can change is the background and text colour, the way it highlights seems to be browser dependent). Chrome highlights it using that stupid light grey colour while firefox highlights the options using the regular bright blue colour you'd expect to see.

chrome:
![image](https://user-images.githubusercontent.com/9030085/29653853-7b74fb72-88ee-11e7-9463-7aac996e6ff9.png)

firefox:
![image](https://user-images.githubusercontent.com/9030085/29653872-8fa4ee72-88ee-11e7-9c7e-879fac436f37.png)

Either way, I *will* add it to my theme but I think it would be better off also being in your plugin so it follows any future themes (if there ever is anymore).

**Comment by ntoff** [comment]
multi line select fix: https://github.com/ntoff/Octoprint-CyborgTheme/commit/5a3cad15eeafc305190b6b8af85cd3807be07b54 (still the stripped down branch, please remove and reinstall the plugin to see any changes).

**Comment by jneilliii** [comment]
That definitely worked, and thanks for the recommendation on the css addition for the plugin.  I'll definitely add it.

**Comment by jneilliii** [comment]
Latest release candidate fixes the temperature pull-down issue.
