### ISSUE TITLE
Drag and Drop Interface doesn't go away

### ISSUE THREAD

**Issue by thrasr** [ntoff/Octoprint-CyborgTheme#19]
When dragging a file to another program (discord, in my case) - the drag and drop overlay appears on octoprint.  When the file is released into discord - the drag and drop overlay on octoprint remains.  This behavior does NOT occur when using default octoprint (overlay properly goes away) - only with the cyborg theme.

**Comment by ntoff** [comment]
That's not something I can reproduce, if I drag a file across the browser window and onto discord, the overlay to upload disappears from the browser and discord brings up its own drag & drop overlay. In fact, the overlay for octoprint goes away the instant the file is moved away from the browser (and it doesn't even appear in octoprint unless I drag the file over octoprint).

Which browser are you using, octoprint version and version of the theme?

**Comment by thrasr** [comment]
A bit more testing has it happening a bit differently than I thought.  The easiest way to reproduce for me is to have octoprint in the background partially covered by the file explorer.  Drag image from that file window over the octoprint window and back and they file upload overlay won't go away.

This bit of refined testing to reproduce it actually shows that this *does* happen without the cyborg theme as well!  So looks like its an octoprint issue.  Sorry about that.  Closing this.

**Comment by ntoff** [comment]
>So looks like its an octoprint issue.

Gonna have to say I can't reproduce it that way either, on OctoPrint 1.3.5 (which is the latest version) dragging anything across it will have the overlay instantly go away as soon as the mouse cursor is no longer over the browser (Chrome) window. 

I tried half covering OctoPrint with explorer, dragging an image onto discord (didn't upload to discord because I don't want to spam a random channel with images) and the instant my mouse cursor leaves the browser window and moves on to discord, the overlay is gone.

Which version of OctoPrint are you using?

**Comment by thrasr** [comment]
I'm on OctoPrint 1.3.5 using Firefox 56.0.1.  It may just be a lag thing on my side?  

Try half covering OctoPrint with explorer, drag an image over OctoPrint and then back to the explorer.  I only saw it because I was dragging images to discord - but it isn't needed to reproduce.  If I leave OctoPrint from the sides of firefox, it works fine.  Its only when I leave Octoprint to another window from the middle.

**Comment by ntoff** [comment]
huh, strange, you're right, but only in firefox, and only if you don't leave via the side of the browser, Chrome works fine both ways. This is something you'll probably have to bring up on OctoPrint's issue tracker, though I'm not sure it's something OctoPrint is doing, or just a quirk of Firefox not detecting the mouse cursor has left its window properly (Chrome doesn't seem to exhibit this behaviour).

**Comment by thrasr** [comment]
Glad to hear it isn't just me.  I'll open an issue on OctoPrint's repo so they can track it.  Thanks for testing it out and reproducing it!
