### ISSUE TITLE
Temperature inputs are hard to read

### ISSUE THREAD

**Issue by AlexSwensen** [ntoff/Octoprint-CyborgTheme#8]
All inputs (and selects) should probably have a style applied to them that is easy to read in all cases.
Currently its hard to read (most notably the temperature inputs).

I can work on a PR to solve this if you like

**Comment by ntoff** [comment]
I'll take a look at it. The inputs are black text on white while you're editing them but yeah most of the time they're a dull grey colour and I guess might be a bit hard to see. Weirdly, all the inputs in the settings dialog seem to be fine.

**Comment by ntoff** [comment]
ok I've made some changes: https://github.com/ntoff/Octoprint-CyborgTheme/commit/633784fdd7a7c8006c5b54a5e4dec308f2fe2256

edit: image of what it looks like now in chrome. Placeholder text is darker

![image](https://cloud.githubusercontent.com/assets/9030085/24564832/d083a142-1696-11e7-87eb-1b51100910d5.png)


@AlexSwensen I'm sorry but there's no auto update in place, you'll have to uninstall and then reinstall the plugin to update it.

Incidentally, that "impossible to read" behaviour is standard for the theme https://bootswatch.com/2/cyborg/ as that text is meant to be placeholder text (and as such _should_ be nearly impossible to read), it seems octoprint is using placeholder text as actual text. @foosel :(

**Comment by AlexSwensen** [comment]
Cool. I'll check this out. Sadly i'll be traveling through the weekend, but when i get back i'll test out the new version. While placeholder text has subtle differences, it should be distinct enough for most of us to be able to read. (as is demonstrated in the link you posted)

Your screenshot does look much better though. I'll post feedback once i have had an opportunity to test.

Regarding updates, should be possible to solve for that soon as well. More than happy to look into this with you.

**Comment by ntoff** [comment]
really? the placeholder text in the link to the actual cyborg theme source is nearly invisible to me. I guess different monitors render it differently.

Either way it should hopefully be fixed now, been having trouble with my  dev pc so hopefully if THAT's also fixed, maybe I'll look into the releases and auto updates stuff. I'm not a programmer by  trade and all this github stuff is sort of confusing to me.

**Comment by AlexSwensen** [comment]
I can see the text perfectly fine in your screenshot and your link on my Macbook Pro, so it should be fine for many users.

Regarding github, if that becomes an issue I'm happy to pitch in. OctoPrint really needs a nice dark theme, and I'm happy to contribute where i can.

**Comment by ntoff** [comment]
Thanks, and yeah I didn't realise how much I wanted a dark theme until a request for one popped up. It really helps for those late night print jobs, not being blinded by the bright white page.

I'll leave the honour of closing this up to you once you've tested it (if the changes are satisfactory). I've tested it on my PC and on an android tablet and it seems ok, the only macbook I have access to is pre-retina so I doubt it'd render much differently to my PC.

**Comment by AlexSwensen** [comment]
Looks good! 👍
